import type { Metadata } from "next";

import localfont from "next/font/local";
import "./globals.css";

const futura = localfont({
  src: [
    {
      path: "../public/fonts/futura-bold.ttf",
    },
  ],
  variable: "--font-futura",
});

const futuraThin = localfont({
  src: [
    {
      path: "../public/fonts/futura-thin.ttf",
    },
  ],
  variable: "--font-futura-thin",
});

export const metadata: Metadata = {
  title: "Anesu's Daily-wrap",
  icons: {
    icon: "/spotifylogo.png",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${futura.variable} ${futuraThin.variable} bg-black `}>
        {children}
        <footer>
          <hr className="md:mx-28 mt-10 border-zinc-800" />
          <div className="flex justify-between mt-10">
            <p className="font-light text-xs md:mx-28">
              &copy;{new Date().getFullYear()} Anesu Nyakonda
            </p>
            <div className="flex space-x-5">
              <p className="font-light text-xs   underline">
                Terms & conditions
              </p>
              <p className="font-light text-xs underline pr-10">
                Privacy Policy
              </p>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
